[package]
authors = ["nrayamajhee <nishan@rayamajhee.com>"]
edition = "2018"
name = "webshell"
version = "0.1.0"

[dependencies]
fixedbitset = "0.1.9"
js-sys = "0.3.22"
wasm-bindgen = "0.2.45"

[dependencies.web-sys]
version = "0.3.22"
features = [
  'Window',
  'Document',
  'HtmlBodyElement',
  'EventTarget',
  'CssStyleDeclaration',
  'HtmlStyleElement',
  'DomTokenList',
  'MouseEvent',
  'Event',
  'HtmlHeadElement',
  'HtmlElement',
  'Node',
  'console',
  'DomRect',
  'DomRectReadOnly',
  'HtmlCanvasElement',
  'Element',
  'CanvasRenderingContext2d',
]

[dependencies.console_error_panic_hook]
optional = true
version = "0.1.6"

[dependencies.wee_alloc]
optional = true
version = "0.4.4"

[dev-dependencies]
wasm-bindgen-test = "0.2.45"

[features]
default = ["console_error_panic_hook"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile]
[profile.release]
opt-level = "s"

[profile.release.wee_alloc]
optional = true
version = "0.4.4"
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.4", optional = true }