name: Build, test and deploy Moksha to github pages
on:
    push:
        branches:
            - master
jobs:
    build-test-deploy:
        runs-on: ubuntu-latest
        
        container:
            image: docker://nrayamajhee/arch-wasm-pack
        
        steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Build and Test
          run: |
            rustup default nightly
            cd moksha
            wasm-pack build
            wasm-pack test --headless --chrome
       
        - name: Deploy to Github Pages
          uses: JamesIves/github-pages-deploy-action@master
          env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BRANCH: gh-pages
            FOLDER: 'www/dist'
            CNAME: moksha.rayamajhee.com
            BUILD_SCRIPT: cd www && npm install && npm run build && cd ..
